"""add pool members and workspace/ttl wiring to sandboxes

Revision ID: 7f07c054e570
Revises: d10dc67d3bce
Create Date: 2026-07-29 20:12:29.576851

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f07c054e570'
down_revision: Union[str, Sequence[str], None] = 'd10dc67d3bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_ref', sa.String(length=255), nullable=False),
    sa.Column('weight_class', sa.String(length=16), nullable=False),
    sa.Column('backend', sa.String(length=16), nullable=False),
    sa.Column('native_ref', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint('uq_pool_state_key', 'pool_state', ['image_digest', 'weight_class'])
    op.add_column('sandboxes', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.add_column('sandboxes', sa.Column('idle_ttl_seconds', sa.Integer(), nullable=True))
    op.add_column('sandboxes', sa.Column('max_ttl_seconds', sa.Integer(), nullable=True))
    # Named explicitly (autogenerate left it as None, which Postgres would auto-name —
    # but drop_constraint on downgrade needs an actual name to target, not None).
    op.create_foreign_key(
        'fk_sandboxes_workspace_id_workspaces', 'sandboxes', 'workspaces', ['workspace_id'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_sandboxes_workspace_id_workspaces', 'sandboxes', type_='foreignkey')
    op.drop_column('sandboxes', 'max_ttl_seconds')
    op.drop_column('sandboxes', 'idle_ttl_seconds')
    op.drop_column('sandboxes', 'workspace_id')
    op.drop_constraint('uq_pool_state_key', 'pool_state', type_='unique')
    op.drop_table('pool_members')
    # ### end Alembic commands ###
