"""phase 9: api key display/usage metadata and run status/async fields

Revision ID: 9a1c4e77b210
Revises: 4657775fb046
Create Date: 2026-08-28 20:40:00.000000

Hand-written rather than autogenerated (unlike every migration before it): this session
had no reachable Postgres when the schema change was made, and `alembic revision
--autogenerate` against a throwaway SQLite database hung partway through replaying the
existing history. Every operation here is a plain additive `add_column`/`drop_column`
pair, which is exactly the shape autogenerate would have emitted — see the checklist's
Phase 9 notes for the upgrade/downgrade verification this was put through against real
Postgres.

Two groups of columns, both additive and all nullable-or-defaulted, so the migration is
safe to apply to a populated database and safe to roll back:

* `api_keys` — `prefix`, `created_by_user_id`, `last_used_at`. Needed for
  `POST/GET/DELETE /v1/api-keys` (doc §11's key management, previously impossible
  outside a direct DB insert): something to display in a listing, who minted it, and
  whether it's still in use before someone revokes it.
* `runs` — `status`, `component_ref`, `error`, `finished_at`. Needed for doc §5.1's
  `?async=true` + `GET /v1/runs/{run_id}` poll contract, which had never been built: a
  run row now exists *before* the run finishes, so it needs a lifecycle status and a
  place to record a control-plane failure that produced no result at all.

`runs.status` is added with a server default of `'completed'` precisely so existing rows
get the right value: before this phase a `runs` row was only ever written *after* a run
finished, so every historical row genuinely is a completed run.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a1c4e77b210"
down_revision: Union[str, Sequence[str], None] = "4657775fb046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("api_keys", sa.Column("prefix", sa.String(length=16), nullable=True))
    op.add_column("api_keys", sa.Column("created_by_user_id", sa.String(length=36), nullable=True))
    op.add_column("api_keys", sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        "fk_api_keys_created_by_user_id_users",
        "api_keys",
        "users",
        ["created_by_user_id"],
        ["id"],
    )

    op.add_column(
        "runs",
        sa.Column("status", sa.String(length=16), nullable=False, server_default="completed"),
    )
    op.add_column("runs", sa.Column("component_ref", sa.String(length=255), nullable=True))
    op.add_column("runs", sa.Column("error", sa.Text(), nullable=True))
    op.add_column("runs", sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("runs", "finished_at")
    op.drop_column("runs", "error")
    op.drop_column("runs", "component_ref")
    op.drop_column("runs", "status")

    op.drop_constraint("fk_api_keys_created_by_user_id_users", "api_keys", type_="foreignkey")
    op.drop_column("api_keys", "last_used_at")
    op.drop_column("api_keys", "created_by_user_id")
    op.drop_column("api_keys", "prefix")
