"""add sidecar_refs to sandboxes

Revision ID: abcaabfd20d0
Revises: f3b826b15c91
Create Date: 2026-07-18 17:09:26.214413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abcaabfd20d0'
down_revision: Union[str, Sequence[str], None] = 'f3b826b15c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows (15 present in dev at the time this was
    # written) — every sandbox created before Phase 5 has no sidecars anyway, so `{}`
    # is the correct historical value, not just a placeholder.
    op.add_column(
        'sandboxes',
        sa.Column('sidecar_refs', sa.JSON(), nullable=False, server_default='{}'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sandboxes', 'sidecar_refs')
    # ### end Alembic commands ###
