"""add builds table

Revision ID: d10dc67d3bce
Revises: abcaabfd20d0
Create Date: 2026-07-19 20:58:19.579038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd10dc67d3bce'
down_revision: Union[str, Sequence[str], None] = 'abcaabfd20d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('builds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('component_name', sa.String(length=128), nullable=False),
    sa.Column('component_version', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('image_ref', sa.String(length=255), nullable=True),
    sa.Column('artifact_ref', sa.String(length=255), nullable=True),
    sa.Column('log_excerpt', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('builds')
    # ### end Alembic commands ###
